apiVersion: v2
name: healthcare-app
description: A Helm chart for Healthcare Application with Patient and Appointment services
type: application
version: 0.1.0
appVersion: "2.1.0"

# Add these required fields
maintainers:
  - name: kamalakar
    email: kamalakarj78@gmail.com
