{{- if .Values.patientService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "patient-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.patientService.service.type }}
  ports:
    - port: {{ .Values.patientService.service.port }}
      targetPort: {{ .Values.patientService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: patient-service
    version: {{ .Values.global.tag | default "latest" }}
{{- end }}