apiVersion: v1
kind: PersistentVolume
metadata:
  name: patient-logs-pv-dev
  namespace: healthcare-ns-dev
  labels:
    type: azurefile
    app: patient-service
    environment: "dev"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-file-secret-dev
    shareName: patient-logs-share-dev
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-logs-pvc-dev
  namespace: healthcare-ns-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile
  selector:
    matchLabels:
      app: patient-service
      environment: "dev"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appointment-logs-pv-dev
  namespace: healthcare-ns-dev
  labels:
    type: azurefile
    app: appointment-service
    environment: "dev"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: azure-file-secret-dev
    shareName: appointment-logs-share-dev
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appointment-logs-pvc-dev
  namespace: healthcare-ns-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile
  selector:
    matchLabels:
      app: appointment-service
      environment: "dev"