apiVersion: v1
kind: Secret
metadata:
  name: healthcare-app-secrets
  namespace: healthcare-ns
type: Opaque
data:
  # These should be base64 encoded
  # echo -n "your-secret" | base64
  acr-username: aGVhbHRoY2FyZWFwcGFjcjE2MDY4OQ==
  acr-password: U2krdjhnZWRCRFZOSDJHWEd1d29acUpxNUN3UnpqOVE1WFNTWDloVU9SK0FDUkRaT3N2TQ==