global:
  environment: staging

patientService:
  replicaCount: 3
  tag: latest
  serviceType: ClusterIP
  hpa:
    minReplicas: 2
    maxReplicas: 8

appointmentService:
  replicaCount: 3
  tag: latest
  serviceType: ClusterIP
  hpa:
    minReplicas: 2
    maxReplicas: 8

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: lbg-app.staging.example.com

persistence:
  enabled: true
  size: 5Gi
  storageClass: "managed-premium"

image:
  credentials:
    username: "acrlbgdemodev"
    password: "cLbic1o0qQPT+vHBDsGWzFBZ+WAN9x+Q5jnPd9DDgK+ACRCLJ5Lt"
