global:
  environment: prod

patientService:
  replicaCount: 4
  tag: latest
  serviceType: ClusterIP
  hpa:
    minReplicas: 3
    maxReplicas: 10

appointmentService:
  replicaCount: 4
  tag: latest
  serviceType: ClusterIP
  hpa:
    minReplicas: 3
    maxReplicas: 10

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: lbg-app.prod.example.com

persistence:
  enabled: true
  size: 10Gi
  storageClass: "managed-premium"

image:
  credentials:
    username: "acrlbgdemodev"
    password: "cLbic1o0qQPT+vHBDsGWzFBZ+WAN9x+Q5jnPd9DDgK+ACRCLJ5Lt"
