{{- if .Values.appointmentService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appointmentService.service.type }}
  ports:
    - port: {{ .Values.appointmentService.service.port }}
      targetPort: {{ .Values.appointmentService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: appointment-service
    version: {{ .Values.global.tag | default "latest" }}
{{- end }}